services:
  # Production Environment
  - type: web
    name: moveo-frontend-prod
    env: static
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production

  # Development Environment
  - type: web
    name: moveo-frontend-dev
    env: static
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: development
